INSERT INTO USERS (ID, USERNAME, PASSWORD, ROLE)
VALUES (1, 'user1', '$2a$10$D9ugnEhW4.HvX/HLWIy3t.QxkC51.hjZGt5RJ5UNFCyFZwBmvase2', 'USER');

INSERT INTO USERS (ID, USERNAME, PASSWORD, ROLE)
VALUES (2, 'admin', '$2a$10$wANyhh3FLGSRHsn08XRtUeQm70EIdVmRVuMSSjmUaGdfJUu.2ccHq', 'ADMIN');
